import{_ as n,c as e,a,o as i}from"./app-DdES4ywf.js";const t="/imgs/python/segmentationfault.png",l="/imgs/python/segmentationfault-gdb.png",p={};function o(d,s){return i(),e("div",null,[...s[0]||(s[0]=[a('<h2 id="现象" tabindex="-1"><a class="header-anchor" href="#现象"><span>现象</span></a></h2><p>今天在升级一个Python虚拟环境的时候，出现了这种错误 <code>OSError - setuptools pip wheel failed with error code -11</code>。我的操作步骤是这样的，先删除虚拟环境<code>rm -rf env</code>，再创建 <code>virtualenv env --python=python3</code>，没什么问题。看到退出码 <code>11</code>，查了下毫无头绪。在外部python3 的环境下执行了下 <code>pip3 list</code>, 报如下错误：</p><p><img src="'+t+`" alt=""></p><h2 id="分析调试" tabindex="-1"><a class="header-anchor" href="#分析调试"><span>分析调试</span></a></h2><p>看到错误<code>Segmentation fault</code>，突然想起之前看过董大的一篇文章 <a href="https://www.dongwm.com/post/debug-segmentation-fault/" target="_blank" rel="noopener noreferrer">一次调试段错误(segmentation fault)的经验</a>，很明显这是一个段错误。</p><p>考虑将pip，卸载重新安装。</p><div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212;"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code"><code class="language-"><span class="line"><span>python3 -m pip uninstall pip</span></span>
<span class="line"><span>wget https://bootstrap.pypa.io/get-pip.py</span></span>
<span class="line"><span>python3 get-pip.py</span></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>但在安装的时候，直接就报错误<code>Segmentation fault</code>，便退出了。那便调试下吧，看看具体是哪里的问题。</p><p><strong>段错误 (segmentation fault)</strong> 一般是由于 C 模块试图访问无法访问的内存引起的。我们都知道Python很多模块底层都调用C语言的接口，也就不难理解为什么会出现段错误了。但是仅适用Python的调试器的话，是无法调试该种错误的，它像上边一样只返回 <code>Segmentation fault</code>字样，并不会返回具体的错误信息和调用栈。此时我们需要调试工具<code>gdb</code>，<code>gdb</code>是<code>gcc</code>的调试工具，一般用来调试c/c++程序，该工具是支持python的，可以调试python到c的整个调用栈。</p><p><code>gdb</code>可通过<code>yum install gdb</code>安装 , 在bash 窗口输入<code>gdb</code> 启动<code>gdb</code>调试窗口，可以通过<code>run</code> 命令来运行我们的py文件。</p><p>使用gdb调试查看得到如下信息：</p><p><img src="`+l+`" alt=""></p><p>可以看到是库 <code>libcrypto.so</code>的问题。更多<code>gdb</code>介绍可参考扩展阅读。</p><h2 id="解决" tabindex="-1"><a class="header-anchor" href="#解决"><span>解决</span></a></h2><p>python3.7 的ssl 对openssl版本有要求，必须用openssl并且版本必须大于等于1.02或者libressl2.64。</p><p>之前安装的 openssl-1.1.0，这次安装libressl试试。操作如下：</p><div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212;"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code"><code class="language-"><span class="line"><span># 安装libressl-2.8.0</span></span>
<span class="line"><span>wget https://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-2.8.0.tar.gz</span></span>
<span class="line"><span>tar zxvf libressl-2.8.0.tar.gz</span></span>
<span class="line"><span>cd libressl-2.8.0/</span></span>
<span class="line"><span>./configure --prefix=/usr/local/ssllib</span></span>
<span class="line"><span>make</span></span>
<span class="line"><span>make install</span></span>
<span class="line"><span></span></span>
<span class="line"><span># 创建配置文件</span></span>
<span class="line"><span>cd /etc/ld.so.conf.d</span></span>
<span class="line"><span>vim libressl-2.8.0.conf</span></span>
<span class="line"><span></span></span>
<span class="line"><span># 将以下行加入文件，并保存</span></span>
<span class="line"><span>/usr/local/ssllib</span></span>
<span class="line"><span></span></span>
<span class="line"><span>ldconfig -v #重新加载库文件</span></span>
<span class="line"><span></span></span>
<span class="line"><span># 把原来的命令建立新的硬连接</span></span>
<span class="line"><span>mv /usr/bin/openssl /usr/bin/openssl.bak</span></span>
<span class="line"><span>mv /usr/include/openssl /usr/include/openssl.bak</span></span>
<span class="line"><span>ln -s /usr/local/ssllib/bin/openssl /usr/bin/openssl</span></span>
<span class="line"><span>ln -s /usr/local/ssllib/include/openssl /usr/include/openssl</span></span>
<span class="line"><span></span></span>
<span class="line"><span># 运行命令看是否成功</span></span>
<span class="line"><span>openssl version</span></span>
<span class="line"><span>libressl-2.8.0</span></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>重新编译Python3.7.3，安装解决。</p><div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" style="--shiki-light:#393a34;--shiki-dark:#dbd7caee;--shiki-light-bg:#ffffff;--shiki-dark-bg:#121212;"><pre class="shiki shiki-themes vitesse-light vitesse-dark vp-code"><code class="language-"><span class="line"><span>./configure --with-ensurepip=install</span></span>
<span class="line"><span>make &amp;&amp; make install</span></span></code></pre><div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0;"><div class="line-number"></div><div class="line-number"></div></div></div><h2 id="总结" tabindex="-1"><a class="header-anchor" href="#总结"><span>总结</span></a></h2><p>在Python中<code>段错误</code>一般出现在编译安装模块时，解决它的思路是：先考虑升级出现段错误的模块包。如果未解决问题，可通过<code>gdb</code>来调试定位问题，根据具体问题具体解决。</p><h2 id="扩展阅读" tabindex="-1"><a class="header-anchor" href="#扩展阅读"><span>扩展阅读</span></a></h2><ul><li>https://en.wikipedia.org/wiki/Segmentation_fault</li><li>https://devguide.python.org/gdb/</li><li>https://www.dongwm.com/post/debug-segmentation-fault</li><li>https://linuxtools-rst.readthedocs.io/zh_CN/latest/tool/gdb.html</li><li>https://www.gnu.org/software/gdb/</li></ul>`,23)])])}const c=n(p,[["render",o]]),m=JSON.parse('{"path":"/pages/ab7a86/","title":"Python 段错误（Segmentation fault）排查","lang":"zh-CN","frontmatter":{"title":"Python 段错误（Segmentation fault）排查","tags":["Python","Segementation fault"],"permalink":"/pages/ab7a86/","createTime":"2023/09/08 17:36:02","description":"现象 今天在升级一个Python虚拟环境的时候，出现了这种错误 OSError - setuptools pip wheel failed with error code -11。我的操作步骤是这样的，先删除虚拟环境rm -rf env，再创建 virtualenv env --python=python3，没什么问题。看到退出码 11，查了下毫无头绪...","head":[["script",{"type":"application/ld+json"},"{\\"@context\\":\\"https://schema.org\\",\\"@type\\":\\"Article\\",\\"headline\\":\\"Python 段错误（Segmentation fault）排查\\",\\"image\\":[\\"https://pylixm.top/imgs/python/segmentationfault.png\\",\\"https://pylixm.top/imgs/python/segmentationfault-gdb.png\\"],\\"dateModified\\":\\"2025-09-30T08:57:49.000Z\\",\\"author\\":[]}"],["meta",{"property":"og:url","content":"https://pylixm.top/pages/ab7a86/"}],["meta",{"property":"og:site_name","content":"底层逻辑"}],["meta",{"property":"og:title","content":"Python 段错误（Segmentation fault）排查"}],["meta",{"property":"og:description","content":"现象 今天在升级一个Python虚拟环境的时候，出现了这种错误 OSError - setuptools pip wheel failed with error code -11。我的操作步骤是这样的，先删除虚拟环境rm -rf env，再创建 virtualenv env --python=python3，没什么问题。看到退出码 11，查了下毫无头绪..."}],["meta",{"property":"og:type","content":"article"}],["meta",{"property":"og:image","content":"https://pylixm.top/imgs/python/segmentationfault.png"}],["meta",{"property":"og:locale","content":"zh-CN"}],["meta",{"property":"og:updated_time","content":"2025-09-30T08:57:49.000Z"}],["meta",{"property":"article:tag","content":"Segementation fault"}],["meta",{"property":"article:tag","content":"Python"}],["meta",{"property":"article:modified_time","content":"2025-09-30T08:57:49.000Z"}]]},"readingTime":{"minutes":2.36,"words":709},"git":{"createdTime":1759222669000,"updatedTime":1759222669000,"contributors":[{"name":"pylixm","username":"pylixm","email":"pyli.xm@gmail.com","commits":1,"avatar":"https://avatars.githubusercontent.com/pylixm?v=4","url":"https://github.com/pylixm"}]},"autoDesc":true,"filePathRelative":"01.开发语言/01.Python/01.语言特性/16.Python-advance-segmentation-fault.md","headers":[],"categoryList":[{"id":"59843f","sort":1,"name":"开发语言"},{"id":"9d2a49","sort":1,"name":"Python"},{"id":"406962","sort":1,"name":"语言特性"}]}');export{c as comp,m as data};
